Exercícios

1. Utilizando o dataframe sobre falhas em máquinas, crie um programa para retornar a média as colunas com valores númericos e não numéricos fazer a contagem das informações que se repetem.

2. Utilizando o mesmo dataframe, crie um programa para calcular a média, soma, min, max e mediana e retornar estas informações em um único dataframe.

3. Crie um programa para retornar os dados a qual o torque tenha valores maiores do que 50.

4. Crie uma função para retornar apenas as máquinas do tipo m com todas as falhas, menos o estado sem falha (No Failure).

In [2]:
import pandas as pd

In [10]:
df = pd.read_csv('./manutencao_preditiva.csv')
df

,UDI,ID Produto,Tipo,Temperatura Ar [K],Temperatura Processo [K],Velocidade Rotacao [rpm],Torque [Nm],Desgaste Ferramenta [min],Alvo,Tipo da Falha
0,1,M14860,M,298.1,308.6,1551,42.8,0,0,No Failure
1,2,L47181,L,298.2,308.7,1408,46.3,3,0,No Failure
2,3,L47182,L,298.1,308.5,1498,49.4,5,0,No Failure
3,4,L47183,L,298.2,308.6,1433,39.5,7,0,No Failure
4,5,L47184,L,298.2,308.7,1408,40.0,9,0,No Failure
...,...,...,...,...,...,...,...,...,...,...
9995,9996,M24855,M,298.8,308.4,1604,29.5,14,0,No Failure
9996,9997,H39410,H,298.9,308.4,1632,31.8,17,0,No Failure
9997,9998,M24857,M,299.0,308.6,1645,33.4,22,0,No Failure
9998,9999,H39412,H,299.0,308.7,1408,48.5,25,0,No Failure
9999,10000,M24859,M,299.0,308.7,1500,40.2,30,0,No Failure

In [23]:
df['dif_(%)'] = (abs(df['Temperatura Ar [K]'] - df['Temperatura Processo [K]']) / df['Temperatura Ar [K]']) *100
df

,UDI,ID Produto,Tipo,Temperatura Ar [K],Temperatura Processo [K],Velocidade Rotacao [rpm],Torque [Nm],Desgaste Ferramenta [min],Alvo,Tipo da Falha,dif,dif_(%)
0,1,M14860,M,298.1,308.6,1551,42.8,0,0,No Failure,-3.522308,3.522308
1,2,L47181,L,298.2,308.7,1408,46.3,3,0,No Failure,-3.521127,3.521127
2,3,L47182,L,298.1,308.5,1498,49.4,5,0,No Failure,-3.488762,3.488762
3,4,L47183,L,298.2,308.6,1433,39.5,7,0,No Failure,-3.487592,3.487592
4,5,L47184,L,298.2,308.7,1408,40.0,9,0,No Failure,-3.521127,3.521127
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,M24855,M,298.8,308.4,1604,29.5,14,0,No Failure,-3.212851,3.212851
9996,9997,H39410,H,298.9,308.4,1632,31.8,17,0,No Failure,-3.178321,3.178321
9997,9998,M24857,M,299.0,308.6,1645,33.4,22,0,No Failure,-3.210702,3.210702
9998,9999,H39412,H,299.0,308.7,1408,48.5,25,0,No Failure,-3.244147,3.244147
9999,10000,M24859,M,299.0,308.7,1500,40.2,30,0,No Failure,-3.244147,3.244147